# Generated by Django 5.1.5 on 2025-02-19 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_delete_orders'),
        ('profiles', '0005_remove_customer_basket_id_remove_customer_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='basket_orders',
            new_name='basket_order',
        ),
        migrations.AddField(
            model_name='orders',
            name='shipping_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkout.shippinginfo'),
        ),
    ]
