# Generated by Django 5.1.5 on 2025-07-07 08:06

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_order_shipping_order_order_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='basket_order',
            field=models.ForeignKey(null=True, blank=True, on_delete=models.SET_NULL, to='checkout.Basket'),
        ),
    ]
