# Generated by Django 5.1.5 on 2025-02-13 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='county',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='date',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='street_address1',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='street_address2',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='town_or_city',
        ),
    ]
