# Generated by Django 5.1.5 on 2025-02-05 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_remove_basket_product_id_basket_grand_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='customer_id',
            new_name='basket_customer',
        ),
    ]
