# Generated by Django 5.1.5 on 2025-02-06 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_rename_customer_id_basket_basket_customer'),
        ('products', '0003_rename_products_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='products',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='basket_customer',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='grand_total',
        ),
        migrations.AddField(
            model_name='basket',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.DeleteModel(
            name='BasketItem',
        ),
    ]
