# Generated by Django 5.1.5 on 2025-02-18 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_orders_country_orders_date_orders_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='basket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_basket', to='checkout.basket'),
        ),
    ]
