# Generated by Django 5.1.5 on 2025-02-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_remove_basket_products_remove_basket_basket_customer_and_more'),
        ('products', '0003_rename_products_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='product',
        ),
        migrations.AddField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(related_name='baskets', to='products.product'),
        ),
    ]
