# Generated by Django 5.1.5 on 2025-02-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_remove_basket_basket_id_basket_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='basket_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
