# Generated by Django 5.1.5 on 2025-02-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_basket_basket_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='basket_id',
        ),
    ]
