# Generated by Django 5.1.5 on 2025-02-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_shippinginfo_remove_orders_product'),
        ('profiles', '0005_remove_customer_basket_id_remove_customer_order_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
