# Generated by Django 5.1.5 on 2025-06-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0015_delete_order'),
        ('profiles', '0011_remove_order_shipping_order_order_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingInfo',
        ),
    ]
