# Generated by Django 5.1.5 on 2025-02-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='size',
            new_name='flavor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stocked',
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
