# Generated by Django 5.1.5 on 2025-02-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_initial'),
        ('products', '0002_alter_products_product_id'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
