# Generated by Django 5.1.5 on 2025-02-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_size_product_flavor_remove_product_stocked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flavor',
            field=models.CharField(blank=True, choices=[('SOUR', 'Sour'), ('SWEET', 'Sweet'), ('FRUTIY', 'Fruity')], max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('STICKY', 'Sticky'), ('HARD', 'Hard'), ('GUMMY', 'Gummy'), ('CHOCOLATE', 'Chocolate')], max_length=254, null=True),
        ),
    ]
